apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ template "spring-demo.fullname" . }}-deployment
spec:
    replicas: {{ .Values.scale }}
    selector:
        matchLabels:
            app: {{ template "spring-demo.fullname" . }}-spring
    template:
        metadata:
            labels:
                app: {{ template "spring-demo.fullname" . }}-spring
        spec:
            containers:
            - name: {{ template "spring-demo.fullname" . }}-spring
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullSecrets:
            - name: {{ template "spring-demo.fullname" . }}-acr-secret              
              ports:
                - containerPort: 8080
              env: 
                - name: MYSQL_DATA_SOURCE
                  value: mysql:://{{ template "mysql.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:3306/{{ .Values.mysqlDatabase }}
                - name: JWT_SECRET
                  value: {{ .Values.jwt.secret }}
              envFrom:    
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                        name: {{ template "mysql.fullname" . }}
                        key: mysql-password 