apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "spring-demo.fullname" . }}-env
data:
  SPRING_PROFILE: {{ .Values.spring.profile }}
  MYSQL_USERNAME: {{ .Values.mysql.mysqlUser }}
  MYSQL_DATA_SOURCE: jdbc:mysql://{{ .Release.Name }}-mysql.{{ .Release.Namespace }}.svc.cluster.local:3306/{{ .Values.mysql.mysqlDatabase }}