apiVersion: v1
kind: Secret
metadata:
    name: {{ template "spring-demo.fullname" . }}-acr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
    name: {{ template "spring-demo.fullname" . }}-jwt-secret
type: Opaque
data:
  jwt-secret: {{ template "jwtSecret" . }}