apiVersion: v1
kind: Secret
metadata:
    name: {{ template "spring-demo.fullname" . }}-acr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}    

---

piVersion: v1
kind: Secret
metadata:
  name: {{ template "spring-demo.fullname" . }}-mysql-secret
type: Opaque
data:
  username: {{ template "mysqlUserName" . }}
  password: {{ template "mysqlPassword" . }}