kind: Service
apiVersion: v1
metadata:
    name: {{ template "spring-demo.fullname" . }}-service
spec:
    type: LoadBalancer
    selector: 
        app: {{ template "spring-demo.fullname" . }}-spring
    ports:
        - port: 7070
          targetPort: 8080