kind: Service
apiVersion: v1
metadata:
    name: {{ template "spring-demo.fullname" . }}-service
    annotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
    type: LoadBalancer
    selector: 
        app: {{ template "spring-demo.fullname" . }}-spring
    ports:
        - name: spring
          port: 7070
          targetPort: 8080